"""
Contoh integrasi AI model untuk generate.py
Copy-paste salah satu fungsi ini ke generate.py sesuai kebutuhan.
"""

from datetime import datetime
import os


# ============================================
# CONTOH 1: OpenAI API
# ============================================
def generate_with_openai():
    """
    Contoh menggunakan OpenAI API
    Install: pip install openai
    """
    try:
        import openai
        
        openai.api_key = os.getenv("OPENAI_API_KEY")
        
        response = openai.ChatCompletion.create(
            model="gpt-4",
            messages=[
                {"role": "system", "content": "You are a helpful assistant that generates daily summaries."},
                {"role": "user", "content": "Generate a brief daily summary for today."}
            ],
            max_tokens=500
        )
        
        summary = f"""# Daily Summary

Generated at **{datetime.now().strftime('%Y-%m-%d %H:%M')}**.

{response.choices[0].message.content}

---
*Generated by OpenAI GPT-4*
"""
        return summary
    except ImportError:
        print("OpenAI not installed. Install with: pip install openai")
        return None


# ============================================
# CONTOH 2: Ollama (AI Lokal)
# ============================================
def generate_with_ollama():
    """
    Contoh menggunakan Ollama (AI lokal, gratis)
    Install: pip install ollama
    Setup: https://ollama.ai
    """
    try:
        import ollama
        
        response = ollama.generate(
            model="llama2",  # atau model lain yang sudah diinstall
            prompt="Generate a brief daily summary for today."
        )
        
        summary = f"""# Daily Summary

Generated at **{datetime.now().strftime('%Y-%m-%d %H:%M')}**.

{response['response']}

---
*Generated by Ollama (Local AI)*
"""
        return summary
    except ImportError:
        print("Ollama not installed. Install with: pip install ollama")
        return None


# ============================================
# CONTOH 3: Hugging Face Transformers
# ============================================
def generate_with_huggingface():
    """
    Contoh menggunakan Hugging Face Transformers
    Install: pip install transformers torch
    """
    try:
        from transformers import pipeline
        
        generator = pipeline("text-generation", model="gpt2")
        
        prompt = f"Daily summary for {datetime.now().strftime('%Y-%m-%d')}:"
        result = generator(prompt, max_length=200, num_return_sequences=1)
        
        summary = f"""# Daily Summary

Generated at **{datetime.now().strftime('%Y-%m-%d %H:%M')}**.

{result[0]['generated_text']}

---
*Generated by Hugging Face Transformers*
"""
        return summary
    except ImportError:
        print("Transformers not installed. Install with: pip install transformers torch")
        return None


# ============================================
# CONTOH 4: Custom API (REST)
# ============================================
def generate_with_custom_api():
    """
    Contoh menggunakan custom API endpoint
    Install: pip install requests
    """
    try:
        import requests
        
        api_url = "https://your-api-endpoint.com/generate"
        api_key = os.getenv("CUSTOM_API_KEY")
        
        response = requests.post(
            api_url,
            json={"prompt": "Generate daily summary"},
            headers={"Authorization": f"Bearer {api_key}"}
        )
        
        data = response.json()
        
        summary = f"""# Daily Summary

Generated at **{datetime.now().strftime('%Y-%m-%d %H:%M')}**.

{data.get('summary', 'No summary generated')}

---
*Generated by Custom API*
"""
        return summary
    except ImportError:
        print("Requests not installed. Install with: pip install requests")
        return None


# ============================================
# CONTOH 5: Template dengan Data External
# ============================================
def generate_with_template():
    """
    Contoh generate summary dengan template dan data external
    Bisa digabungkan dengan API, database, atau file lain
    """
    now = datetime.now()
    
    # Contoh: baca data dari file, database, atau API
    # tasks = read_tasks_from_file()
    # metrics = get_system_metrics()
    
    summary = f"""# Daily Summary

Generated at **{now.strftime('%Y-%m-%d %H:%M')}**.

## Date
- **Date:** {now.strftime('%A, %B %d, %Y')}
- **Time:** {now.strftime('%H:%M:%S')}

## Tasks Completed
- Task 1: Completed
- Task 2: In Progress
- Task 3: Pending

## System Status
- Status: ✅ Operational
- Uptime: 99.9%
- No errors detected

## Notes
- All systems running normally
- Scheduled maintenance completed
- No issues reported

---
*Generated by AI Worker*
"""
    return summary


# ============================================
# CARA MENGGUNAKAN:
# ============================================
"""
1. Pilih salah satu fungsi di atas
2. Copy fungsi tersebut ke generate.py
3. Ganti fungsi generate_summary() di generate.py dengan fungsi yang dipilih
4. Install dependencies yang diperlukan
5. Set environment variables jika diperlukan (API keys, dll)
6. Jalankan: python generate.py
"""

