import time
from datetime import datetime
import os
from pathlib import Path

# Import AI HTML generator
try:
    from .ai_html_generator import generate_html_css_with_ai
    HAS_AI_GENERATOR = True
except ImportError:
    try:
        from ai_html_generator import generate_html_css_with_ai
        HAS_AI_GENERATOR = True
    except ImportError:
        HAS_AI_GENERATOR = False

# Konfigurasi AI (bisa diubah)
USE_AI = True  # Set False untuk selalu pakai template
AI_PROVIDER = "gemini"  # "gemini", "openai", "ollama", "anthropic", atau "auto"
THEME = "modern"  # "modern", "classic", "minimal", "dark", dll
STYLE = "gradient"  # "gradient", "solid", "glassmorphism", dll

def generate_html_css_project(project_dir, date_str, use_ai=None, ai_provider=None, theme=None, style=None):
    """
    Generate HTML/CSS project menggunakan AI atau template fallback
    
    Args:
        project_dir: Directory untuk project
        date_str: Tanggal project
        use_ai: Gunakan AI (default: USE_AI)
        ai_provider: Provider AI (default: AI_PROVIDER)
        theme: Tema design (default: THEME)
        style: Style CSS (default: STYLE)
    """
    use_ai = use_ai if use_ai is not None else (USE_AI and HAS_AI_GENERATOR)
    ai_provider = ai_provider or AI_PROVIDER
    theme = theme or THEME
    style = style or STYLE
    
    html_content = None
    css_content = None
    
    # Coba generate dengan AI jika enabled
    if use_ai:
        try:
            html_content, css_content = generate_html_css_with_ai(
                date_str,
                ai_provider=ai_provider,
                theme=theme,
                style=style
            )
            if html_content and css_content:
                print(f"✅ Generated with AI ({ai_provider})")
        except Exception as e:
            print(f"⚠️ AI generation failed: {e}, using template")
    
    # Fallback ke template jika AI tidak tersedia atau gagal
    if not html_content or not css_content:
        # Template HTML
        html_content = f"""<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project - {date_str}</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container">
        <header>
            <h1>🎨 Project {date_str}</h1>
            <p class="subtitle">Generated by AI Daily Summary Generator</p>
        </header>
        
        <main>
            <section class="card">
                <h2>Welcome!</h2>
                <p>Ini adalah proyek HTML/CSS sederhana yang dibuat secara otomatis pada <strong>{date_str}</strong>.</p>
            </section>
            
            <section class="card">
                <h2>Features</h2>
                <ul>
                    <li>✅ Responsive Design</li>
                    <li>✅ Modern CSS Styling</li>
                    <li>✅ Clean Code Structure</li>
                    <li>✅ Auto-generated Content</li>
                </ul>
            </section>
            
            <section class="card">
                <h2>About</h2>
                <p>Proyek ini dibuat secara otomatis oleh AI Worker sebagai bagian dari daily summary generator.</p>
                <p>Setiap generate akan membuat folder baru dengan proyek HTML/CSS yang unik.</p>
            </section>
        </main>
        
        <footer>
            <p>&copy; {datetime.now().strftime('%Y')} AI Daily Summary Generator</p>
        </footer>
    </div>
</body>
</html>
"""
    
    # Template CSS
    css_content = """/* Modern CSS Styling */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    line-height: 1.6;
    color: #333;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    min-height: 100vh;
    padding: 20px;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    background: white;
    border-radius: 20px;
    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
    overflow: hidden;
}

header {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 40px;
    text-align: center;
}

header h1 {
    font-size: 2.5em;
    margin-bottom: 10px;
    text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);
}

.subtitle {
    font-size: 1.1em;
    opacity: 0.9;
}

main {
    padding: 40px;
}

.card {
    background: #f8f9fa;
    border-radius: 15px;
    padding: 30px;
    margin-bottom: 30px;
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
    transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.card:hover {
    transform: translateY(-5px);
    box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);
}

.card h2 {
    color: #667eea;
    margin-bottom: 15px;
    font-size: 1.8em;
}

.card p {
    margin-bottom: 15px;
    color: #555;
    font-size: 1.1em;
}

.card ul {
    list-style: none;
    padding-left: 0;
}

.card ul li {
    padding: 10px 0;
    padding-left: 30px;
    position: relative;
    font-size: 1.1em;
}

.card ul li:before {
    content: "→";
    position: absolute;
    left: 0;
    color: #667eea;
    font-weight: bold;
}

footer {
    background: #2c3e50;
    color: white;
    text-align: center;
    padding: 20px;
    margin-top: 40px;
}

footer p {
    margin: 0;
}

/* Responsive Design */
@media (max-width: 768px) {
    header h1 {
        font-size: 2em;
    }
    
    main {
        padding: 20px;
    }
    
    .card {
        padding: 20px;
    }
}
"""
    
    # Tulis file HTML
    html_path = project_dir / "index.html"
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    
    # Tulis file CSS
    css_path = project_dir / "style.css"
    with open(css_path, "w", encoding="utf-8") as f:
        f.write(css_content)
    
    return html_path, css_path

def generate_summary():
    """
    Generate daily summary dan HTML/CSS project.
    Setiap generate akan membuat folder baru dengan nama berdasarkan tanggal.
    """
    now = datetime.now()
    now_str = now.strftime("%Y-%m-%d %H:%M")
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H-%M")
    
    # Buat folder project berdasarkan tanggal
    # Format: YYYY-MM-DD-HH-MM
    project_folder_name = f"{date_str}-{time_str}"  # Format: 2025-01-17-14-30
    base_dir = Path(__file__).parent.parent
    projects_dir = base_dir / "projects"
    project_dir = projects_dir / project_folder_name
    
    # Buat folder project
    os.makedirs(project_dir, exist_ok=True)
    
    # Generate HTML/CSS project
    html_path, css_path = generate_html_css_project(project_dir, date_str)
    
    # Generate summary markdown (opsional, untuk tracking)
    summary = f"""# Daily Summary - {date_str}

Generated at **{now_str}**.

## Project Created
- Folder: `{project_folder_name}`
- HTML: `index.html`
- CSS: `style.css`

## Project Details
- Location: `{project_dir}`
- Files: 2 files (HTML + CSS)

---
*Generated by AI Worker*
"""
    
    # Pastikan folder data ada
    os.makedirs("../data", exist_ok=True)
    
    # Tulis summary (opsional)
    file_path = "../data/daily_summary.md"
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(summary)
    
    print(f"[{now_str}] Project created: {project_folder_name} ({html_path.name}, {css_path.name})")

if __name__ == "__main__":
    print("AI Worker started. Generating summary every 30 minutes...")
    print("Press Ctrl+C to stop.")
    
    while True:
        try:
            generate_summary()
            time.sleep(1800)  # 30 menit = 1800 detik
        except KeyboardInterrupt:
            print("\nAI Worker stopped.")
            break
        except Exception as e:
            print(f"Error: {e}")
            time.sleep(60)  # Tunggu 1 menit jika error

