"""
Gemini Project Generator - GUI Version dengan System Tray
Berjalan di background dengan icon di system tray
Generate AI projects menggunakan Google Gemini Flash 2.0
"""
import time
import threading
import os
import sys
from datetime import datetime
from pathlib import Path

# Import AI HTML generator
try:
    from .ai_html_generator import generate_html_css_with_ai
    HAS_AI_GENERATOR = True
except ImportError:
    try:
        from ai_html_generator import generate_html_css_with_ai
        HAS_AI_GENERATOR = True
    except ImportError:
        HAS_AI_GENERATOR = False
        print("AI HTML generator not available. Using template fallback.")

try:
    import pystray
    from PIL import Image, ImageDraw
    HAS_PYSTRAY = True
except ImportError:
    HAS_PYSTRAY = False
    print("Warning: pystray not installed. Install with: pip install pystray pillow")

try:
    import tkinter as tk
    from tkinter import messagebox, scrolledtext
    HAS_TKINTER = True
except ImportError:
    HAS_TKINTER = False
    print("Warning: tkinter not available")


def safe_print(*args, **kwargs):
    """Print dengan handling emoji untuk Windows console"""
    try:
        print(*args, **kwargs)
    except UnicodeEncodeError:
        # Remove emoji jika tidak bisa di-print
        safe_args = []
        for arg in args:
            if isinstance(arg, str):
                safe_arg = arg.encode('ascii', 'ignore').decode('ascii')
                safe_args.append(safe_arg)
            else:
                safe_args.append(arg)
        print(*safe_args, **kwargs)


class AIWorker:
    """Class untuk handle AI worker logic"""
    
    def __init__(self, data_dir=None, use_ai=True, ai_provider="gemini", theme="modern", style="gradient", 
                 auto_push=False, github_token=None, push_to_showcase=False, showcase_repo_path=None,
                 showcase_repo_url=None, showcase_branch="main"):
        self.running = False
        self.thread = None
        self.interval = 1800  # 30 menit default
        self.data_dir = data_dir or self._get_data_dir()
        self.last_update = None
        self.status_callback = None
        self.use_ai = use_ai and HAS_AI_GENERATOR
        self.ai_provider = ai_provider
        self.theme = theme
        self.style = style
        self.auto_push = auto_push
        self.github_token = github_token or os.getenv("GITHUB_TOKEN") or os.getenv("GITHUB_TOKEN_PAT") or os.getenv("GITHUBTOKENPAT")
        self.push_to_showcase = push_to_showcase
        # Folder showcase ada di parent directory: ../ai-showcase/ (sama level dengan AiCommitBot)
        # Repo showcase: https://github.com/MarioSitepu/Jack-s-Cards
        self.showcase_repo_path = showcase_repo_path or os.getenv("SHOWCASE_REPO_PATH", "../Project-Showcase")
        self.showcase_repo_url = showcase_repo_url or os.getenv("SHOWCASE_REPO_URL", "https://github.com/MarioSitepu/Jack-s-Cards.git")
        self.showcase_branch = showcase_branch or os.getenv("SHOWCASE_BRANCH", "main")
        
    def _get_data_dir(self):
        """Get data directory relative to script location"""
        if getattr(sys, 'frozen', False):
            # Running as compiled exe
            base_dir = Path(sys.executable).parent
        else:
            # Running as script
            base_dir = Path(__file__).parent.parent
        data_dir = base_dir / "data"
        # Ensure directory exists
        data_dir.mkdir(exist_ok=True)
        return data_dir
    
    def generate_html_css_project(self, project_dir, date_str):
        """Generate HTML/CSS project menggunakan AI atau template fallback"""
        html_content = None
        css_content = None
        
        # Coba generate dengan AI jika enabled
        if self.use_ai:
            try:
                html_content, css_content = generate_html_css_with_ai(
                    date_str, 
                    ai_provider=self.ai_provider,
                    theme=self.theme,
                    style=self.style
                )
                if html_content and css_content:
                    if self.status_callback:
                        self.status_callback(f"✅ Generated with AI ({self.ai_provider})")
            except Exception as e:
                if self.status_callback:
                    self.status_callback(f"⚠️ AI generation failed: {e}, using template")
        
        # Fallback ke template jika AI tidak tersedia atau gagal
        if not html_content or not css_content:
            # Template HTML
            html_content = f"""<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project - {date_str}</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container">
        <header>
            <h1>🎨 Project {date_str}</h1>
            <p class="subtitle">Generated by AI Daily Summary Generator</p>
        </header>
        
        <main>
            <section class="card">
                <h2>Welcome!</h2>
                <p>Ini adalah proyek HTML/CSS sederhana yang dibuat secara otomatis pada <strong>{date_str}</strong>.</p>
            </section>
            
            <section class="card">
                <h2>Features</h2>
                <ul>
                    <li>✅ Responsive Design</li>
                    <li>✅ Modern CSS Styling</li>
                    <li>✅ Clean Code Structure</li>
                    <li>✅ Auto-generated Content</li>
                </ul>
            </section>
            
            <section class="card">
                <h2>About</h2>
                <p>Proyek ini dibuat secara otomatis oleh AI Worker sebagai bagian dari daily summary generator.</p>
                <p>Setiap generate akan membuat folder baru dengan proyek HTML/CSS yang unik.</p>
            </section>
        </main>
        
        <footer>
            <p>&copy; {datetime.now().strftime('%Y')} AI Daily Summary Generator</p>
        </footer>
    </div>
</body>
</html>
"""
        
        # Template CSS
        css_content = """/* Modern CSS Styling */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    line-height: 1.6;
    color: #333;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    min-height: 100vh;
    padding: 20px;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    background: white;
    border-radius: 20px;
    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
    overflow: hidden;
}

header {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 40px;
    text-align: center;
}

header h1 {
    font-size: 2.5em;
    margin-bottom: 10px;
    text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);
}

.subtitle {
    font-size: 1.1em;
    opacity: 0.9;
}

main {
    padding: 40px;
}

.card {
    background: #f8f9fa;
    border-radius: 15px;
    padding: 30px;
    margin-bottom: 30px;
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
    transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.card:hover {
    transform: translateY(-5px);
    box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);
}

.card h2 {
    color: #667eea;
    margin-bottom: 15px;
    font-size: 1.8em;
}

.card p {
    margin-bottom: 15px;
    color: #555;
    font-size: 1.1em;
}

.card ul {
    list-style: none;
    padding-left: 0;
}

.card ul li {
    padding: 10px 0;
    padding-left: 30px;
    position: relative;
    font-size: 1.1em;
}

.card ul li:before {
    content: "→";
    position: absolute;
    left: 0;
    color: #667eea;
    font-weight: bold;
}

footer {
    background: #2c3e50;
    color: white;
    text-align: center;
    padding: 20px;
    margin-top: 40px;
}

footer p {
    margin: 0;
}

/* Responsive Design */
@media (max-width: 768px) {
    header h1 {
        font-size: 2em;
    }
    
    main {
        padding: 20px;
    }
    
    .card {
        padding: 20px;
    }
}
"""
        
        # Tulis file HTML
        html_path = project_dir / "index.html"
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html_content)
        
        # Tulis file CSS
        css_path = project_dir / "style.css"
        with open(css_path, "w", encoding="utf-8") as f:
            f.write(css_content)
        
        return html_path, css_path
    
    def generate_summary(self):
        """Generate daily summary dan HTML/CSS project"""
        now = datetime.now()
        now_str = now.strftime("%Y-%m-%d %H:%M")
        date_str = now.strftime("%Y-%m-%d")
        time_str = now.strftime("%H-%M")
        
        # Buat folder project berdasarkan tanggal
        # Format: YYYY-MM-DD atau YYYY-MM-DD-HH-MM (jika ingin lebih spesifik)
        project_folder_name = f"{date_str}-{time_str}"  # Format: 2025-01-17-14-30
        
        # Hitung showcase_path terlebih dahulu (akan digunakan nanti untuk push)
        showcase_path = None
        if self.push_to_showcase:
            # Path ke showcase repo
            showcase_path = Path(self.showcase_repo_path)
            if not showcase_path.is_absolute():
                if getattr(sys, 'frozen', False):
                    base_dir = Path(sys.executable).parent
                else:
                    base_dir = Path(__file__).parent.parent
                showcase_path = base_dir.parent / self.showcase_repo_path.replace("../", "")
        
        # Langsung save ke Project-Showcase jika push_to_showcase enabled
        if self.push_to_showcase and showcase_path:
            projects_dir = showcase_path / "projects"
            project_dir = projects_dir / project_folder_name
            
            # Juga copy ke public/projects untuk Vercel deployment
            public_projects_dir = showcase_path / "public" / "projects"
            public_project_dir = public_projects_dir / project_folder_name
        else:
            # Fallback ke projects di AiCommitBot jika showcase tidak enabled
            projects_dir = self.data_dir.parent / "projects"
            project_dir = projects_dir / project_folder_name
            public_project_dir = None
        
        # Buat folder project
        os.makedirs(project_dir, exist_ok=True)
        if public_project_dir:
            os.makedirs(public_project_dir, exist_ok=True)
        
        # Generate HTML/CSS project
        html_path, css_path = self.generate_html_css_project(project_dir, date_str)
        
        # Copy ke public/projects jika showcase enabled
        if public_project_dir:
            import shutil
            public_html_path = public_project_dir / "index.html"
            public_css_path = public_project_dir / "style.css"
            shutil.copy2(html_path, public_html_path)
            shutil.copy2(css_path, public_css_path)
            if self.status_callback:
                self.status_callback(f"📁 Also saved to public/projects: {public_project_dir}")
        
        # Generate summary markdown (opsional, untuk tracking)
        summary = f"""# Daily Summary - {date_str}

Generated at **{now_str}**.

## Project Created
- Folder: `{project_folder_name}`
- HTML: `index.html`
- CSS: `style.css`

## Project Details
- Location: `{project_dir}`
- Files: 2 files (HTML + CSS)

---
*Generated by AI Worker*
"""
        
        # Pastikan folder data ada
        os.makedirs(self.data_dir, exist_ok=True)
        
        # Tulis summary (opsional)
        summary_path = self.data_dir / "daily_summary.md"
        with open(summary_path, "w", encoding="utf-8") as f:
            f.write(summary)
        
        self.last_update = now
        log_msg = f"[{now_str}] Project created: {project_folder_name} ({html_path.name}, {css_path.name})"
        print(log_msg)
        
        if self.status_callback:
            self.status_callback(log_msg)
        
        # Verifikasi file benar-benar dibuat
        if not html_path.exists() or not css_path.exists():
            error_msg = f"❌ ERROR: Files not created! HTML exists: {html_path.exists()}, CSS exists: {css_path.exists()}"
            safe_print(error_msg)
            if self.status_callback:
                self.status_callback(error_msg)
            return log_msg
        
        if self.status_callback:
            self.status_callback(f"✅ Files verified: Both HTML and CSS exist")
        
        # Auto push ke GitHub jika enabled
        if self.auto_push:
            try:
                try:
                    from .git_helper import git_commit_and_push
                except ImportError:
                    from git_helper import git_commit_and_push
                
                repo_path = self.data_dir.parent
                success, message = git_commit_and_push(
                    repo_path=repo_path,
                    files_to_add=["data/", "projects/"],
                    commit_message=f"🤖 AI update: New project {project_folder_name}",
                    token=self.github_token
                )
                
                if success:
                    push_msg = f"✅ Pushed to GitHub: {message}"
                    safe_print(push_msg)
                    if self.status_callback:
                        self.status_callback(push_msg)
                else:
                    error_msg = f"⚠️ Push failed: {message}"
                    safe_print(error_msg)
                    if self.status_callback:
                        self.status_callback(error_msg)
            except Exception as e:
                error_msg = f"⚠️ Auto-push error: {str(e)}"
                safe_print(error_msg)
                if self.status_callback:
                    self.status_callback(error_msg)
        
        # Push ke Showcase Repo jika enabled
        if self.push_to_showcase and showcase_path:
            try:
                # Path ke showcase repo (sudah dihitung di atas)
                if not showcase_path.exists():
                    error_msg = f"⚠️ Showcase path does not exist: {showcase_path}"
                    safe_print(error_msg)
                    if self.status_callback:
                        self.status_callback(error_msg)
                    return log_msg
                
                # Cek apakah ini git repo
                git_dir = showcase_path / ".git"
                if not git_dir.exists():
                    error_msg = f"⚠️ Showcase path is not a git repository: {showcase_path}"
                    safe_print(error_msg)
                    if self.status_callback:
                        self.status_callback(error_msg)
                    return log_msg
                
                safe_print(f"📁 Showcase repo path: {showcase_path}")
                if self.status_callback:
                    self.status_callback(f"🚀 Starting git commit & push process...")
                
                # Git commit & push langsung
                import subprocess
                
                # Configure git user
                subprocess.run(
                    ["git", "config", "user.name", "AI-Bot"],
                    cwd=showcase_path,
                    capture_output=True,
                    timeout=5
                )
                subprocess.run(
                    ["git", "config", "user.email", "ai-bot@example.com"],
                    cwd=showcase_path,
                    capture_output=True,
                    timeout=5
                )
                
                # Generate gallery index jika ada fungsi untuk itu
                try:
                    try:
                        from .showcase_helper import generate_gallery_index
                    except ImportError:
                        try:
                            from showcase_helper import generate_gallery_index
                            generate_gallery_index(showcase_path)
                            index_path = showcase_path / "index.html"
                            if index_path.exists():
                                if self.status_callback:
                                    self.status_callback(f"✅ Gallery index created")
                        except ImportError:
                            pass  # showcase_helper tidak tersedia, skip
                except Exception as e:
                    if self.status_callback:
                        self.status_callback(f"⚠️ Error generating gallery index: {str(e)}")
                
                # Add files (hanya file yang ada)
                safe_print(f"📝 Adding files to git...")
                if self.status_callback:
                    self.status_callback(f"📝 Adding files to git...")
                
                # Cek apakah index.html ada
                index_html_path = showcase_path / "index.html"
                files_to_add = ["projects/", "public/projects/"]
                if index_html_path.exists():
                    files_to_add.append("index.html")
                    print(f"   Adding: projects/, public/projects/, and index.html")
                else:
                    print(f"   Adding: projects/ and public/projects/")
                
                add_result = subprocess.run(
                    ["git", "add"] + files_to_add,
                    cwd=showcase_path,
                    capture_output=True,
                    text=True,
                    timeout=10
                )
                if add_result.returncode != 0:
                    safe_print(f"⚠️ Git add warning: {add_result.stderr}")
                    # Retry dengan hanya projects/ jika index.html error
                    if "index.html" in add_result.stderr:
                        print(f"   Retrying with only projects/...")
                        add_result = subprocess.run(
                            ["git", "add", "projects/"],
                            cwd=showcase_path,
                            capture_output=True,
                            text=True,
                            timeout=10
                        )
                
                # Commit
                commit_msg = f"🎨 Add project: {project_folder_name}"
                commit_result = subprocess.run(
                    ["git", "commit", "-m", commit_msg],
                    cwd=showcase_path,
                    capture_output=True,
                    text=True,
                    timeout=10
                )
                
                if commit_result.returncode == 0:
                    safe_print(f"✅ Committed: {commit_msg}")
                    if self.status_callback:
                        self.status_callback(f"✅ Committed: {commit_msg}")
                    
                    # Push dengan token
                    if self.github_token:
                        if self.status_callback:
                            self.status_callback(f"🔑 Using GitHub token for push")
                        # Update remote URL dengan token
                        remote_result = subprocess.run(
                            ["git", "remote", "get-url", "origin"],
                            cwd=showcase_path,
                            capture_output=True,
                            text=True,
                            timeout=5
                        )
                        
                        if remote_result.returncode == 0:
                            remote_url = remote_result.stdout.strip()
                            if "github.com" in remote_url and "x-access-token" not in remote_url:
                                if remote_url.startswith("https://") and "@" not in remote_url:
                                    repo_part = remote_url.replace("https://github.com/", "").replace(".git", "")
                                    new_url = f"https://x-access-token:{self.github_token}@github.com/{repo_part}.git"
                                    subprocess.run(
                                        ["git", "remote", "set-url", "origin", new_url],
                                        cwd=showcase_path,
                                        capture_output=True,
                                        timeout=5
                                    )
                    
                    # Push
                    if self.status_callback:
                        self.status_callback(f"🚀 Pushing to origin/{self.showcase_branch}...")
                    push_result = subprocess.run(
                        ["git", "push", "origin", self.showcase_branch],
                        cwd=showcase_path,
                        capture_output=True,
                        text=True,
                        timeout=30
                    )
                    
                    if push_result.returncode == 0:
                        showcase_msg = f"✅ Successfully pushed to Showcase Repo: {project_folder_name}"
                        safe_print(showcase_msg)
                        if self.status_callback:
                            self.status_callback(showcase_msg)
                    else:
                        error_msg = f"❌ Push failed: {push_result.stderr}"
                        safe_print(error_msg)
                        if self.status_callback:
                            self.status_callback(error_msg)
                else:
                    if "nothing to commit" in commit_result.stdout.lower() or "nothing to commit" in commit_result.stderr.lower():
                        info_msg = f"ℹ️ No changes to commit"
                        safe_print(info_msg)
                        if self.status_callback:
                            self.status_callback(info_msg)
                    else:
                        error_msg = f"❌ Commit failed: {commit_result.stderr}"
                        safe_print(error_msg)
                        if self.status_callback:
                            self.status_callback(error_msg)
            except Exception as e:
                error_msg = f"❌ Showcase push error: {str(e)}"
                safe_print(error_msg)
                import traceback
                traceback.print_exc()
                if self.status_callback:
                    self.status_callback(error_msg)
        
        return log_msg
    
    def worker_loop(self):
        """Main worker loop"""
        while self.running:
            try:
                if self.status_callback:
                    self.status_callback(f"🔄 Starting generation cycle...")
                self.generate_summary()
                
                if self.status_callback:
                    self.status_callback(f"⏳ Waiting {self.interval} seconds until next generation...")
                
                # Sleep dengan check running status setiap detik
                for _ in range(self.interval):
                    if not self.running:
                        break
                    # Sleep dengan check running setiap 0.1 detik untuk responsif
                    for _ in range(10):  # 10 x 0.1 = 1 detik total
                        if not self.running:
                            break
                        time.sleep(0.1)
                    
            except Exception as e:
                error_msg = f"❌ Error in worker loop: {e}"
                safe_print(error_msg)
                import traceback
                traceback.print_exc()
                if self.status_callback:
                    self.status_callback(error_msg)
                # Sleep dengan check running setiap 0.1 detik untuk responsif
                # Tunggu 60 detik sebelum retry jika error
                if self.status_callback:
                    self.status_callback(f"⏳ Waiting 60 seconds before retry...")
                for _ in range(600):  # 600 x 0.1 = 60 detik total
                    if not self.running:
                        break
                    time.sleep(0.1)
    
    def start(self):
        """Start worker"""
        if self.running:
            return False
        
        self.running = True
        # Daemon thread akan otomatis mati saat main thread exit
        self.thread = threading.Thread(target=self.worker_loop, daemon=True)
        self.thread.start()
        return True
    
    def stop(self):
        """Stop worker - fast stop"""
        self.running = False
        if self.thread and self.thread.is_alive():
            # Tunggu thread selesai dengan timeout pendek (1 detik)
            self.thread.join(timeout=1.0)
            # Jika masih hidup setelah timeout, biarkan daemon thread mati sendiri
        return True
    
    def is_running(self):
        """Check if worker is running"""
        return self.running


class SystemTrayApp:
    """System Tray Application"""
    
    def __init__(self, auto_push=False, github_token=None):
        # Get auto_push dari environment atau parameter
        auto_push = auto_push or os.getenv("AUTO_PUSH", "false").lower() == "true"
        github_token = github_token or os.getenv("GITHUB_TOKEN") or os.getenv("GITHUB_TOKEN_PAT") or os.getenv("GITHUBTOKENPAT")
        push_to_showcase = os.getenv("PUSH_TO_SHOWCASE", "false").lower() == "true"
        showcase_repo_path = os.getenv("SHOWCASE_REPO_PATH", "../Project-Showcase")
        showcase_repo_url = os.getenv("SHOWCASE_REPO_URL", "https://github.com/MarioSitepu/Jack-s-Cards.git")
        showcase_branch = os.getenv("SHOWCASE_BRANCH", "main")
        
        self.worker = AIWorker(
            auto_push=auto_push, 
            github_token=github_token,
            push_to_showcase=push_to_showcase,
            showcase_repo_path=showcase_repo_path,
            showcase_repo_url=showcase_repo_url,
            showcase_branch=showcase_branch
        )
        # Set push_to_showcase default ke True jika tidak di-set via env
        if not push_to_showcase and os.getenv("PUSH_TO_SHOWCASE") is None:
            self.worker.push_to_showcase = True  # Default enable showcase
        self.worker.status_callback = self.on_status_update
        self.icon = None
        self.status_log = []
        
    def create_icon_image(self):
        """Create icon image for system tray with Gemini theme"""
        # Try to load custom icon first
        script_dir = Path(__file__).parent.parent
        tray_icon_path = script_dir / "tray_icon.png"
        icon_path = script_dir / "icon.png"
        
        if tray_icon_path.exists():
            return Image.open(tray_icon_path)
        elif icon_path.exists():
            icon = Image.open(icon_path)
            return icon.resize((64, 64), Image.Resampling.LANCZOS)
        
        # Fallback: Create icon with Gemini theme
        image = Image.new('RGBA', (64, 64), (0, 0, 0, 0))
        draw = ImageDraw.Draw(image)
        
        # Background gradient circle (purple to pink)
        draw.ellipse([4, 4, 60, 60], fill=(147, 51, 255), outline=(255, 20, 147), width=2)
        
        # Gemini symbol (two connected circles)
        center_x, center_y = 32, 32
        circle_radius = 12
        offset = 8
        
        # Left circle (purple)
        left_circle = [center_x - offset - circle_radius, center_y - circle_radius,
                       center_x - offset + circle_radius, center_y + circle_radius]
        draw.ellipse(left_circle, fill=(147, 51, 255), outline=(255, 255, 255), width=1)
        
        # Right circle (pink)
        right_circle = [center_x + offset - circle_radius, center_y - circle_radius,
                        center_x + offset + circle_radius, center_y + circle_radius]
        draw.ellipse(right_circle, fill=(255, 20, 147), outline=(255, 255, 255), width=1)
        
        # Connection line
        draw.line([center_x - offset, center_y, center_x + offset, center_y], 
                  fill=(255, 255, 255), width=2)
        
        return image
    
    def on_status_update(self, message):
        """Callback untuk status update"""
        # Remove emoji untuk logging (Windows console compatibility)
        safe_message = message.encode('ascii', 'ignore').decode('ascii') if message else message
        self.status_log.append(f"{datetime.now().strftime('%H:%M:%S')} - {safe_message}")
        # Keep only last 50 messages
        if len(self.status_log) > 50:
            self.status_log.pop(0)
    
    def show_status(self, icon=None, item=None):
        """Show status window"""
        if not HAS_TKINTER:
            messagebox.showinfo("Status", "\n".join(self.status_log[-10:]) if self.status_log else "No status yet")
            return
        
        root = tk.Tk()
        root.title("Gemini Project Generator - Status")
        root.geometry("600x400")
        
        # Status info
        info_frame = tk.Frame(root)
        info_frame.pack(fill=tk.X, padx=10, pady=5)
        
        status_text = "🟢 Running" if self.worker.is_running() else "🔴 Stopped"
        tk.Label(info_frame, text=f"Status: {status_text}", font=("Arial", 12, "bold")).pack(side=tk.LEFT)
        
        if self.worker.last_update:
            last_update_str = self.worker.last_update.strftime("%Y-%m-%d %H:%M:%S")
            tk.Label(info_frame, text=f"Last Update: {last_update_str}").pack(side=tk.LEFT, padx=20)
        
        # Log area
        log_frame = tk.Frame(root)
        log_frame.pack(fill=tk.BOTH, expand=True, padx=10, pady=5)
        
        log_text = scrolledtext.ScrolledText(log_frame, wrap=tk.WORD, height=15)
        log_text.pack(fill=tk.BOTH, expand=True)
        log_text.insert(tk.END, "\n".join(self.status_log) if self.status_log else "No logs yet")
        log_text.config(state=tk.DISABLED)
        
        # Buttons
        btn_frame = tk.Frame(root)
        btn_frame.pack(fill=tk.X, padx=10, pady=5)
        
        if self.worker.is_running():
            tk.Button(btn_frame, text="Stop Worker", command=self.stop_worker_gui).pack(side=tk.LEFT, padx=5)
        else:
            tk.Button(btn_frame, text="Start Worker", command=self.start_worker_gui).pack(side=tk.LEFT, padx=5)
        
        tk.Button(btn_frame, text="Close", command=root.destroy).pack(side=tk.RIGHT, padx=5)
        
        root.mainloop()
    
    def start_worker_gui(self):
        """Start worker from GUI"""
        if self.worker.start():
            self.on_status_update("Worker started")
            self.update_menu()
        else:
            messagebox.showwarning("Warning", "Worker is already running")
    
    def stop_worker_gui(self):
        """Stop worker from GUI"""
        if self.worker.stop():
            self.on_status_update("Worker stopped")
            self.update_menu()
        else:
            messagebox.showwarning("Warning", "Worker is not running")
    
    def start_worker(self, icon=None, item=None):
        """Start worker from tray menu"""
        if self.worker.start():
            self.on_status_update("Worker started")
            self.update_menu()
    
    def stop_worker(self, icon=None, item=None):
        """Stop worker from tray menu"""
        if self.worker.stop():
            self.on_status_update("Worker stopped")
            self.update_menu()
    
    def update_menu(self):
        """Update tray menu based on worker status"""
        if self.icon:
            menu = self.create_menu()
            self.icon.menu = menu
    
    def create_menu(self):
        """Create system tray menu"""
        status_text = "🟢 Running" if self.worker.is_running() else "🔴 Stopped"
        
        menu_items = [
            pystray.MenuItem(f"Status: {status_text}", None, enabled=False),
            pystray.Menu.SEPARATOR,
            pystray.MenuItem("Show Status", self.show_status),
            pystray.Menu.SEPARATOR,
        ]
        
        if self.worker.is_running():
            menu_items.append(pystray.MenuItem("Stop Worker", self.stop_worker))
        else:
            menu_items.append(pystray.MenuItem("Start Worker", self.start_worker))
        
        menu_items.extend([
            pystray.Menu.SEPARATOR,
            pystray.MenuItem("Exit", self.quit_app)
        ])
        
        return pystray.Menu(*menu_items)
    
    def quit_app(self, icon=None, item=None):
        """Quit application - fast exit"""
        import os
        import sys
        
        # Stop worker dengan timeout pendek
        if self.worker.is_running():
            try:
                # Set flag untuk stop segera
                self.worker.stop()
                # Beri waktu singkat untuk cleanup (max 1 detik)
                import time
                time.sleep(0.5)  # Tunggu 0.5 detik untuk cleanup
            except:
                pass  # Ignore errors saat exit
        
        # Stop icon segera
        if self.icon:
            try:
                self.icon.stop()
            except:
                pass
        
        # Force exit untuk memastikan aplikasi benar-benar keluar
        try:
            os._exit(0)  # Force exit tanpa cleanup lebih lanjut
        except:
            sys.exit(0)  # Fallback ke normal exit
    
    def run(self):
        """Run system tray app"""
        if not HAS_PYSTRAY:
            print("Error: pystray not installed. Cannot run system tray app.")
            print("Install with: pip install pystray pillow")
            return
        
        # Generate summary immediately on start
        self.worker.generate_summary()
        
        # Start worker
        self.worker.start()
        
        # Create icon
        image = self.create_icon_image()
        menu = self.create_menu()
        
        self.icon = pystray.Icon("AI Worker", image, "AI Daily Summary Generator", menu)
        self.icon.run()


def main():
    """Main entry point"""
    print("AI Daily Summary Generator - GUI Version")
    print("Starting system tray application...")
    print("Look for the icon in your system tray (near clock)")
    print("Right-click the icon to access menu")
    
    app = SystemTrayApp()
    try:
        app.run()
    except KeyboardInterrupt:
        print("\nShutting down...")
        app.quit_app()
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()

