import time
from datetime import datetime
import os
import shutil
from pathlib import Path

# Import AI HTML generator
try:
    from .ai_html_generator import generate_html_css_with_ai
    HAS_AI_GENERATOR = True
except ImportError:
    try:
        from ai_html_generator import generate_html_css_with_ai
        HAS_AI_GENERATOR = True
    except ImportError:
        HAS_AI_GENERATOR = False

# Konfigurasi AI (bisa diubah)
USE_AI = True  # Set False untuk selalu pakai template
AI_PROVIDER = "gemini"  # "gemini", "openai", "ollama", "anthropic", atau "auto"
THEME = "modern"  # "modern", "classic", "minimal", "dark", dll
STYLE = "gradient"  # "gradient", "solid", "glassmorphism", dll

# Konfigurasi Auto-Push ke GitHub
AUTO_PUSH = True  # Set True untuk auto push ke GitHub setelah generate
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN") or os.getenv("GITHUB_TOKEN_PAT") or os.getenv("GITHUBTOKENPAT")  # Token untuk push (opsional)

# Konfigurasi Showcase Repo (Repo terpisah untuk showcase website)
# Folder showcase ada di parent directory: ../Project-Showcase/
# Repo showcase: https://github.com/MarioSitepu/Jack-s-Cards
PUSH_TO_SHOWCASE = True  # Set True untuk push ke repo showcase terpisah (default: True - langsung save ke showcase)
SHOWCASE_REPO_PATH = os.getenv("SHOWCASE_REPO_PATH", "../Project-Showcase")  # Path ke folder showcase lokal (sama level dengan AiCommitBot)
SHOWCASE_REPO_URL = os.getenv("SHOWCASE_REPO_URL", "https://github.com/MarioSitepu/Jack-s-Cards.git")  # URL repo showcase GitHub (untuk clone otomatis)
SHOWCASE_BRANCH = os.getenv("SHOWCASE_BRANCH", "main")  # Branch untuk showcase repo

def generate_html_css_project(project_dir, date_str, use_ai=None, ai_provider=None, theme=None, style=None):
    """
    Generate HTML/CSS project menggunakan AI atau template fallback
    
    Args:
        project_dir: Directory untuk project
        date_str: Tanggal project
        use_ai: Gunakan AI (default: USE_AI)
        ai_provider: Provider AI (default: AI_PROVIDER)
        theme: Tema design (default: THEME)
        style: Style CSS (default: STYLE)
    """
    use_ai = use_ai if use_ai is not None else (USE_AI and HAS_AI_GENERATOR)
    ai_provider = ai_provider or AI_PROVIDER
    theme = theme or THEME
    style = style or STYLE
    
    html_content = None
    css_content = None
    
    # Coba generate dengan AI jika enabled
    if use_ai:
        try:
            html_content, css_content = generate_html_css_with_ai(
                date_str,
                ai_provider=ai_provider,
                theme=theme,
                style=style
            )
            if html_content and css_content:
                print(f"✅ Generated with AI ({ai_provider})")
        except Exception as e:
            print(f"⚠️ AI generation failed: {e}, using template")
    
    # Fallback ke template jika AI tidak tersedia atau gagal
    if not html_content or not css_content:
        # Template HTML
        html_content = f"""<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project - {date_str}</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container">
        <header>
            <h1>🎨 Project {date_str}</h1>
            <p class="subtitle">Generated by AI Daily Summary Generator</p>
        </header>
        
        <main>
            <section class="card">
                <h2>Welcome!</h2>
                <p>Ini adalah proyek HTML/CSS sederhana yang dibuat secara otomatis pada <strong>{date_str}</strong>.</p>
            </section>
            
            <section class="card">
                <h2>Features</h2>
                <ul>
                    <li>✅ Responsive Design</li>
                    <li>✅ Modern CSS Styling</li>
                    <li>✅ Clean Code Structure</li>
                    <li>✅ Auto-generated Content</li>
                </ul>
            </section>
            
            <section class="card">
                <h2>About</h2>
                <p>Proyek ini dibuat secara otomatis oleh AI Worker sebagai bagian dari daily summary generator.</p>
                <p>Setiap generate akan membuat folder baru dengan proyek HTML/CSS yang unik.</p>
            </section>
        </main>
        
        <footer>
            <p>&copy; {datetime.now().strftime('%Y')} AI Daily Summary Generator</p>
        </footer>
    </div>
</body>
</html>
"""
    
    # Template CSS
    css_content = """/* Modern CSS Styling */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    line-height: 1.6;
    color: #333;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    min-height: 100vh;
    padding: 20px;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    background: white;
    border-radius: 20px;
    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
    overflow: hidden;
}

header {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 40px;
    text-align: center;
}

header h1 {
    font-size: 2.5em;
    margin-bottom: 10px;
    text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);
}

.subtitle {
    font-size: 1.1em;
    opacity: 0.9;
}

main {
    padding: 40px;
}

.card {
    background: #f8f9fa;
    border-radius: 15px;
    padding: 30px;
    margin-bottom: 30px;
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
    transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.card:hover {
    transform: translateY(-5px);
    box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);
}

.card h2 {
    color: #667eea;
    margin-bottom: 15px;
    font-size: 1.8em;
}

.card p {
    margin-bottom: 15px;
    color: #555;
    font-size: 1.1em;
}

.card ul {
    list-style: none;
    padding-left: 0;
}

.card ul li {
    padding: 10px 0;
    padding-left: 30px;
    position: relative;
    font-size: 1.1em;
}

.card ul li:before {
    content: "→";
    position: absolute;
    left: 0;
    color: #667eea;
    font-weight: bold;
}

footer {
    background: #2c3e50;
    color: white;
    text-align: center;
    padding: 20px;
    margin-top: 40px;
}

footer p {
    margin: 0;
}

/* Responsive Design */
@media (max-width: 768px) {
    header h1 {
        font-size: 2em;
    }
    
    main {
        padding: 20px;
    }
    
    .card {
        padding: 20px;
    }
}
"""
    
    # Tulis file HTML
    html_path = project_dir / "index.html"
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    
    # Tulis file CSS
    css_path = project_dir / "style.css"
    with open(css_path, "w", encoding="utf-8") as f:
        f.write(css_content)
    
    return html_path, css_path

def generate_summary():
    """
    Generate daily summary dan HTML/CSS project.
    Langsung save ke Project-Showcase tanpa simpan di AiCommitBot.
    """
    now = datetime.now()
    now_str = now.strftime("%Y-%m-%d %H:%M")
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H-%M")
    
    # Buat folder project berdasarkan tanggal
    # Format: YYYY-MM-DD-HH-MM
    project_folder_name = f"{date_str}-{time_str}"  # Format: 2025-01-17-14-30
    base_dir = Path(__file__).parent.parent
    
    # Langsung generate ke Project-Showcase (tidak simpan di AiCommitBot)
    showcase_path = Path(SHOWCASE_REPO_PATH)
    if not showcase_path.is_absolute():
        # Relative path dari base_dir
        showcase_path = base_dir.parent / SHOWCASE_REPO_PATH.replace("../", "")
    
    projects_dir = showcase_path / "projects"
    project_dir = projects_dir / project_folder_name
    
    # Buat folder project di showcase
    os.makedirs(project_dir, exist_ok=True)
    
    # Generate HTML/CSS project langsung di showcase
    html_path, css_path = generate_html_css_project(project_dir, date_str)
    
    # Juga copy ke public/projects untuk Vercel deployment
    public_projects_dir = showcase_path / "public" / "projects"
    public_project_dir = public_projects_dir / project_folder_name
    os.makedirs(public_project_dir, exist_ok=True)
    
    # Copy HTML dan CSS ke public/projects
    public_html_path = public_project_dir / "index.html"
    public_css_path = public_project_dir / "style.css"
    shutil.copy2(html_path, public_html_path)
    shutil.copy2(css_path, public_css_path)
    print(f"📁 Also saved to public/projects: {public_project_dir}")
    
    # Generate summary markdown (opsional, untuk tracking) - tetap simpan di AiCommitBot/data
    summary = f"""# Daily Summary - {date_str}

Generated at **{now_str}**.

## Project Created
- Folder: `{project_folder_name}`
- HTML: `index.html`
- CSS: `style.css`

## Project Details
- Location: `{project_dir}` (Showcase Repo)
- Files: 2 files (HTML + CSS)

---
*Generated by AI Worker - Saved directly to Showcase Repo*
"""
    
    # Pastikan folder data ada (untuk tracking)
    data_dir = base_dir / "data"
    os.makedirs(data_dir, exist_ok=True)
    
    # Tulis summary (untuk tracking)
    file_path = data_dir / "daily_summary.md"
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(summary)
    
    print(f"[{now_str}] Project created in Showcase: {project_folder_name} ({html_path.name}, {css_path.name})")
    print(f"📁 Project location: {project_dir}")
    print(f"📄 HTML: {html_path}")
    print(f"📄 CSS: {css_path}")
    
    # Verifikasi file benar-benar dibuat
    if not html_path.exists() or not css_path.exists():
        print(f"❌ ERROR: Files not created! HTML exists: {html_path.exists()}, CSS exists: {css_path.exists()}")
        return
    
    print(f"✅ Files verified: Both HTML and CSS exist")
    
    # Push ke Showcase Repo (wajib karena langsung save di sana)
    if PUSH_TO_SHOWCASE:
        print(f"🚀 Starting git commit & push process...")
        try:
            try:
                from .showcase_helper import push_to_showcase_repo, generate_gallery_index
            except ImportError:
                from showcase_helper import push_to_showcase_repo, generate_gallery_index
            
            # Generate gallery index
            print(f"📝 Generating gallery index...")
            try:
                generate_gallery_index(showcase_path)
                index_path = showcase_path / "index.html"
                if index_path.exists():
                    print(f"✅ Gallery index created: {index_path}")
                else:
                    print(f"⚠️ Warning: Gallery index not created (file not found)")
            except Exception as e:
                print(f"⚠️ Error generating gallery index: {str(e)}")
                import traceback
                traceback.print_exc()
            
            # Git commit & push
            try:
                import subprocess
                
                # Cek apakah showcase_path adalah git repo
                git_dir = showcase_path / ".git"
                if not git_dir.exists():
                    print(f"⚠️ Showcase path is not a git repository: {showcase_path}")
                    print(f"   Please initialize git repo or clone from: {SHOWCASE_REPO_URL}")
                    return
                
                print(f"📁 Showcase repo path: {showcase_path}")
                
                # Configure git user
                subprocess.run(
                    ["git", "config", "user.name", "AI-Bot"],
                    cwd=showcase_path,
                    capture_output=True,
                    timeout=5
                )
                subprocess.run(
                    ["git", "config", "user.email", "ai-bot@example.com"],
                    cwd=showcase_path,
                    capture_output=True,
                    timeout=5
                )
                
                # Verifikasi file benar-benar ada sebelum commit
                print(f"🔍 Verifying files before commit...")
                print(f"   Project dir exists: {project_dir.exists()}")
                print(f"   HTML file exists: {html_path.exists()}")
                print(f"   CSS file exists: {css_path.exists()}")
                
                if not project_dir.exists():
                    print(f"❌ ERROR: Project directory does not exist: {project_dir}")
                    return
                
                if not html_path.exists() or not css_path.exists():
                    print(f"❌ ERROR: Project files missing!")
                    print(f"   HTML: {html_path.exists()}")
                    print(f"   CSS: {css_path.exists()}")
                    return
                
                # Cek status git sebelum add
                status_result = subprocess.run(
                    ["git", "status", "--short"],
                    cwd=showcase_path,
                    capture_output=True,
                    text=True,
                    timeout=5
                )
                status_before = status_result.stdout.strip() if status_result.stdout else 'No changes'
                print(f"📊 Git status (before add): {status_before}")
                
                # Add files (hanya file yang ada)
                print(f"📝 Adding files to git...")
                
                # Cek apakah index.html ada
                index_html_path = showcase_path / "index.html"
                files_to_add = ["projects/", "public/projects/"]
                if index_html_path.exists():
                    files_to_add.append("index.html")
                    print(f"   Adding: projects/, public/projects/, and index.html")
                else:
                    print(f"   Adding: projects/ and public/projects/")
                
                add_result = subprocess.run(
                    ["git", "add"] + files_to_add,
                    cwd=showcase_path,
                    capture_output=True,
                    text=True,
                    timeout=10
                )
                if add_result.returncode != 0:
                    print(f"❌ Git add failed: {add_result.stderr}")
                    # Jangan return, coba lanjutkan dengan hanya projects/
                    if "index.html" in add_result.stderr:
                        print(f"   Retrying with only projects/...")
                        add_result = subprocess.run(
                            ["git", "add", "projects/"],
                            cwd=showcase_path,
                            capture_output=True,
                            text=True,
                            timeout=10
                        )
                        if add_result.returncode != 0:
                            print(f"❌ Git add projects/ also failed: {add_result.stderr}")
                            return
                
                # Cek status setelah add
                status_after = subprocess.run(
                    ["git", "status", "--short"],
                    cwd=showcase_path,
                    capture_output=True,
                    text=True,
                    timeout=5
                )
                staged_files = status_after.stdout.strip() if status_after.stdout else 'No changes'
                print(f"📊 Git status (after add): {staged_files}")
                
                if "No changes" in staged_files or not staged_files:
                    print(f"⚠️ WARNING: No files staged for commit!")
                    print(f"   This might mean files are already committed or git add failed silently")
                    # Cek apakah project folder benar-benar ada di git
                    check_result = subprocess.run(
                        ["git", "ls-files", "projects/"],
                        cwd=showcase_path,
                        capture_output=True,
                        text=True,
                        timeout=5
                    )
                    if check_result.returncode == 0 and project_folder_name in check_result.stdout:
                        print(f"   ℹ️ Project folder already tracked in git")
                        print(f"   Files may already be committed. Skipping commit.")
                        return
                    else:
                        print(f"   ⚠️ Project folder not found in git. This is unexpected.")
                        print(f"   Project path: projects/{project_folder_name}/")
                
                # Commit
                commit_msg = f"🎨 Add project: {project_folder_name}"
                print(f"💾 Committing with message: {commit_msg}")
                result = subprocess.run(
                    ["git", "commit", "-m", commit_msg],
                    cwd=showcase_path,
                    capture_output=True,
                    text=True,
                    timeout=10
                )
                
                print(f"📤 Commit result - Return code: {result.returncode}")
                if result.stdout:
                    print(f"   stdout: {result.stdout.strip()}")
                if result.stderr:
                    print(f"   stderr: {result.stderr.strip()}")
                
                if result.returncode == 0:
                    print(f"✅ Committed successfully: {commit_msg}")
                    
                    # Push
                    if GITHUB_TOKEN:
                        print(f"🔑 Using GitHub token for push")
                        # Update remote URL dengan token
                        remote_result = subprocess.run(
                            ["git", "remote", "get-url", "origin"],
                            cwd=showcase_path,
                            capture_output=True,
                            text=True,
                            timeout=5
                        )
                        
                        if remote_result.returncode == 0:
                            remote_url = remote_result.stdout.strip()
                            print(f"🌐 Current remote: {remote_url}")
                            
                            if "github.com" in remote_url and "x-access-token" not in remote_url:
                                if remote_url.startswith("https://"):
                                    if "@" not in remote_url:
                                        repo_part = remote_url.replace("https://github.com/", "").replace(".git", "")
                                        new_url = f"https://x-access-token:{GITHUB_TOKEN}@github.com/{repo_part}.git"
                                        subprocess.run(
                                            ["git", "remote", "set-url", "origin", new_url],
                                            cwd=showcase_path,
                                            capture_output=True,
                                            timeout=5
                                        )
                                        print(f"🔐 Updated remote URL with token")
                    else:
                        print(f"⚠️ No GitHub token found. Push may fail if repo requires authentication.")
                        print(f"   Set GITHUB_TOKEN, GITHUB_TOKEN_PAT, or GITHUBTOKENPAT environment variable")
                    
                    # Push
                    print(f"🚀 Pushing to origin/{SHOWCASE_BRANCH}...")
                    result = subprocess.run(
                        ["git", "push", "origin", SHOWCASE_BRANCH],
                        cwd=showcase_path,
                        capture_output=True,
                        text=True,
                        timeout=30
                    )
                    
                    if result.returncode == 0:
                        print(f"✅ Successfully pushed to Showcase Repo: {project_folder_name}")
                    else:
                        print(f"❌ Push failed!")
                        print(f"   Error: {result.stderr}")
                        print(f"   Output: {result.stdout}")
                else:
                    if "nothing to commit" in result.stdout.lower() or "nothing to commit" in result.stderr.lower():
                        print(f"ℹ️ No changes to commit (files may already be committed)")
                    else:
                        print(f"❌ Commit failed!")
                        print(f"   Error: {result.stderr}")
                        print(f"   Output: {result.stdout}")
                        
            except Exception as e:
                print(f"❌ Git operation error: {str(e)}")
                import traceback
                traceback.print_exc()
                
        except Exception as e:
            print(f"⚠️ Showcase push error: {str(e)}")
    else:
        print(f"⚠️ PUSH_TO_SHOWCASE is False - Project saved but not pushed")

if __name__ == "__main__":
    print("AI Worker started. Generating summary every 30 minutes...")
    print("Press Ctrl+C to stop.")
    
    while True:
        try:
            generate_summary()
            time.sleep(1800)  # 30 menit = 1800 detik
        except KeyboardInterrupt:
            print("\nAI Worker stopped.")
            break
        except Exception as e:
            print(f"Error: {e}")
            time.sleep(60)  # Tunggu 1 menit jika error

