import time
from datetime import datetime
import os

def generate_summary():
    """
    Generate daily summary dengan AI (contoh dummy).
    Ganti fungsi ini dengan model AI sesungguhnya.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    # Contoh output AI (dummy)
    # TODO: Ganti dengan model AI sesungguhnya (LLM, API, dll)
    summary = f"""# Daily Summary

Generated at **{now}**.

## Tasks Completed
- Task 1 selesai
- Task 2 berjalan baik
- Semua sistem aman

## Notes
- Sistem berjalan normal
- Tidak ada error yang terdeteksi
- Semua komponen berfungsi dengan baik

---
*Generated by AI Worker*
"""

    # Pastikan folder data ada
    os.makedirs("../data", exist_ok=True)
    
    # Tulis ke file
    file_path = "../data/daily_summary.md"
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(summary)
    
    print(f"[{now}] Summary updated: {file_path}")

if __name__ == "__main__":
    print("AI Worker started. Generating summary every 30 minutes...")
    print("Press Ctrl+C to stop.")
    
    while True:
        try:
            generate_summary()
            time.sleep(1800)  # 30 menit = 1800 detik
        except KeyboardInterrupt:
            print("\nAI Worker stopped.")
            break
        except Exception as e:
            print(f"Error: {e}")
            time.sleep(60)  # Tunggu 1 menit jika error

