"""
AI Daily Summary Generator - GUI Version dengan System Tray
Berjalan di background dengan icon di system tray
"""
import time
import threading
import os
import sys
from datetime import datetime
from pathlib import Path

# Import AI HTML generator
try:
    from .ai_html_generator import generate_html_css_with_ai
    HAS_AI_GENERATOR = True
except ImportError:
    try:
        from ai_html_generator import generate_html_css_with_ai
        HAS_AI_GENERATOR = True
    except ImportError:
        HAS_AI_GENERATOR = False
        print("AI HTML generator not available. Using template fallback.")

try:
    import pystray
    from PIL import Image, ImageDraw
    HAS_PYSTRAY = True
except ImportError:
    HAS_PYSTRAY = False
    print("Warning: pystray not installed. Install with: pip install pystray pillow")

try:
    import tkinter as tk
    from tkinter import messagebox, scrolledtext
    HAS_TKINTER = True
except ImportError:
    HAS_TKINTER = False
    print("Warning: tkinter not available")


class AIWorker:
    """Class untuk handle AI worker logic"""
    
    def __init__(self, data_dir=None, use_ai=True, ai_provider="gemini", theme="modern", style="gradient", 
                 auto_push=False, github_token=None):
        self.running = False
        self.thread = None
        self.interval = 1800  # 30 menit default
        self.data_dir = data_dir or self._get_data_dir()
        self.last_update = None
        self.status_callback = None
        self.use_ai = use_ai and HAS_AI_GENERATOR
        self.ai_provider = ai_provider
        self.theme = theme
        self.style = style
        self.auto_push = auto_push
        self.github_token = github_token or os.getenv("GITHUB_TOKEN") or os.getenv("GITHUB_TOKEN_PAT")
        
    def _get_data_dir(self):
        """Get data directory relative to script location"""
        if getattr(sys, 'frozen', False):
            # Running as compiled exe
            base_dir = Path(sys.executable).parent
        else:
            # Running as script
            base_dir = Path(__file__).parent.parent
        data_dir = base_dir / "data"
        # Ensure directory exists
        data_dir.mkdir(exist_ok=True)
        return data_dir
    
    def generate_html_css_project(self, project_dir, date_str):
        """Generate HTML/CSS project menggunakan AI atau template fallback"""
        html_content = None
        css_content = None
        
        # Coba generate dengan AI jika enabled
        if self.use_ai:
            try:
                html_content, css_content = generate_html_css_with_ai(
                    date_str, 
                    ai_provider=self.ai_provider,
                    theme=self.theme,
                    style=self.style
                )
                if html_content and css_content:
                    if self.status_callback:
                        self.status_callback(f"✅ Generated with AI ({self.ai_provider})")
            except Exception as e:
                if self.status_callback:
                    self.status_callback(f"⚠️ AI generation failed: {e}, using template")
        
        # Fallback ke template jika AI tidak tersedia atau gagal
        if not html_content or not css_content:
            # Template HTML
            html_content = f"""<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project - {date_str}</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container">
        <header>
            <h1>🎨 Project {date_str}</h1>
            <p class="subtitle">Generated by AI Daily Summary Generator</p>
        </header>
        
        <main>
            <section class="card">
                <h2>Welcome!</h2>
                <p>Ini adalah proyek HTML/CSS sederhana yang dibuat secara otomatis pada <strong>{date_str}</strong>.</p>
            </section>
            
            <section class="card">
                <h2>Features</h2>
                <ul>
                    <li>✅ Responsive Design</li>
                    <li>✅ Modern CSS Styling</li>
                    <li>✅ Clean Code Structure</li>
                    <li>✅ Auto-generated Content</li>
                </ul>
            </section>
            
            <section class="card">
                <h2>About</h2>
                <p>Proyek ini dibuat secara otomatis oleh AI Worker sebagai bagian dari daily summary generator.</p>
                <p>Setiap generate akan membuat folder baru dengan proyek HTML/CSS yang unik.</p>
            </section>
        </main>
        
        <footer>
            <p>&copy; {datetime.now().strftime('%Y')} AI Daily Summary Generator</p>
        </footer>
    </div>
</body>
</html>
"""
        
        # Template CSS
        css_content = """/* Modern CSS Styling */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    line-height: 1.6;
    color: #333;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    min-height: 100vh;
    padding: 20px;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    background: white;
    border-radius: 20px;
    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
    overflow: hidden;
}

header {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 40px;
    text-align: center;
}

header h1 {
    font-size: 2.5em;
    margin-bottom: 10px;
    text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);
}

.subtitle {
    font-size: 1.1em;
    opacity: 0.9;
}

main {
    padding: 40px;
}

.card {
    background: #f8f9fa;
    border-radius: 15px;
    padding: 30px;
    margin-bottom: 30px;
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
    transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.card:hover {
    transform: translateY(-5px);
    box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);
}

.card h2 {
    color: #667eea;
    margin-bottom: 15px;
    font-size: 1.8em;
}

.card p {
    margin-bottom: 15px;
    color: #555;
    font-size: 1.1em;
}

.card ul {
    list-style: none;
    padding-left: 0;
}

.card ul li {
    padding: 10px 0;
    padding-left: 30px;
    position: relative;
    font-size: 1.1em;
}

.card ul li:before {
    content: "→";
    position: absolute;
    left: 0;
    color: #667eea;
    font-weight: bold;
}

footer {
    background: #2c3e50;
    color: white;
    text-align: center;
    padding: 20px;
    margin-top: 40px;
}

footer p {
    margin: 0;
}

/* Responsive Design */
@media (max-width: 768px) {
    header h1 {
        font-size: 2em;
    }
    
    main {
        padding: 20px;
    }
    
    .card {
        padding: 20px;
    }
}
"""
        
        # Tulis file HTML
        html_path = project_dir / "index.html"
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html_content)
        
        # Tulis file CSS
        css_path = project_dir / "style.css"
        with open(css_path, "w", encoding="utf-8") as f:
            f.write(css_content)
        
        return html_path, css_path
    
    def generate_summary(self):
        """Generate daily summary dan HTML/CSS project"""
        now = datetime.now()
        now_str = now.strftime("%Y-%m-%d %H:%M")
        date_str = now.strftime("%Y-%m-%d")
        time_str = now.strftime("%H-%M")
        
        # Buat folder project berdasarkan tanggal
        # Format: YYYY-MM-DD atau YYYY-MM-DD-HH-MM (jika ingin lebih spesifik)
        project_folder_name = f"{date_str}-{time_str}"  # Format: 2025-01-17-14-30
        projects_dir = self.data_dir.parent / "projects"
        project_dir = projects_dir / project_folder_name
        
        # Buat folder project
        os.makedirs(project_dir, exist_ok=True)
        
        # Generate HTML/CSS project
        html_path, css_path = self.generate_html_css_project(project_dir, date_str)
        
        # Generate summary markdown (opsional, untuk tracking)
        summary = f"""# Daily Summary - {date_str}

Generated at **{now_str}**.

## Project Created
- Folder: `{project_folder_name}`
- HTML: `index.html`
- CSS: `style.css`

## Project Details
- Location: `{project_dir}`
- Files: 2 files (HTML + CSS)

---
*Generated by AI Worker*
"""
        
        # Pastikan folder data ada
        os.makedirs(self.data_dir, exist_ok=True)
        
        # Tulis summary (opsional)
        summary_path = self.data_dir / "daily_summary.md"
        with open(summary_path, "w", encoding="utf-8") as f:
            f.write(summary)
        
        self.last_update = now
        log_msg = f"[{now_str}] Project created: {project_folder_name} ({html_path.name}, {css_path.name})"
        print(log_msg)
        
        if self.status_callback:
            self.status_callback(log_msg)
        
        # Auto push ke GitHub jika enabled
        if self.auto_push:
            try:
                try:
                    from .git_helper import git_commit_and_push
                except ImportError:
                    from git_helper import git_commit_and_push
                
                repo_path = self.data_dir.parent
                success, message = git_commit_and_push(
                    repo_path=repo_path,
                    files_to_add=["data/", "projects/"],
                    commit_message=f"🤖 AI update: New project {project_folder_name}",
                    token=self.github_token
                )
                
                if success:
                    push_msg = f"✅ Pushed to GitHub: {message}"
                    print(push_msg)
                    if self.status_callback:
                        self.status_callback(push_msg)
                else:
                    error_msg = f"⚠️ Push failed: {message}"
                    print(error_msg)
                    if self.status_callback:
                        self.status_callback(error_msg)
            except Exception as e:
                error_msg = f"⚠️ Auto-push error: {str(e)}"
                print(error_msg)
                if self.status_callback:
                    self.status_callback(error_msg)
        
        return log_msg
    
    def worker_loop(self):
        """Main worker loop"""
        while self.running:
            try:
                self.generate_summary()
                
                # Sleep dengan check running status setiap 60 detik
                for _ in range(self.interval):
                    if not self.running:
                        break
                    time.sleep(1)
                    
            except Exception as e:
                error_msg = f"Error: {e}"
                print(error_msg)
                if self.status_callback:
                    self.status_callback(error_msg)
                time.sleep(60)  # Tunggu 1 menit jika error
    
    def start(self):
        """Start worker"""
        if self.running:
            return False
        
        self.running = True
        self.thread = threading.Thread(target=self.worker_loop, daemon=True)
        self.thread.start()
        return True
    
    def stop(self):
        """Stop worker"""
        self.running = False
        if self.thread:
            self.thread.join(timeout=5)
        return True
    
    def is_running(self):
        """Check if worker is running"""
        return self.running


class SystemTrayApp:
    """System Tray Application"""
    
    def __init__(self, auto_push=False, github_token=None):
        # Get auto_push dari environment atau parameter
        auto_push = auto_push or os.getenv("AUTO_PUSH", "false").lower() == "true"
        github_token = github_token or os.getenv("GITHUB_TOKEN") or os.getenv("GITHUB_TOKEN_PAT")
        
        self.worker = AIWorker(auto_push=auto_push, github_token=github_token)
        self.worker.status_callback = self.on_status_update
        self.icon = None
        self.status_log = []
        
    def create_icon_image(self):
        """Create icon image for system tray"""
        # Create a simple icon
        image = Image.new('RGB', (64, 64), color='white')
        draw = ImageDraw.Draw(image)
        
        # Draw a simple robot/AI icon
        # Head
        draw.ellipse([20, 10, 44, 34], fill='blue', outline='black', width=2)
        # Body
        draw.rectangle([18, 34, 46, 54], fill='blue', outline='black', width=2)
        # Eyes
        draw.ellipse([24, 18, 28, 22], fill='white')
        draw.ellipse([36, 18, 40, 22], fill='white')
        
        return image
    
    def on_status_update(self, message):
        """Callback untuk status update"""
        self.status_log.append(f"{datetime.now().strftime('%H:%M:%S')} - {message}")
        # Keep only last 50 messages
        if len(self.status_log) > 50:
            self.status_log.pop(0)
    
    def show_status(self, icon=None, item=None):
        """Show status window"""
        if not HAS_TKINTER:
            messagebox.showinfo("Status", "\n".join(self.status_log[-10:]) if self.status_log else "No status yet")
            return
        
        root = tk.Tk()
        root.title("AI Worker Status")
        root.geometry("600x400")
        
        # Status info
        info_frame = tk.Frame(root)
        info_frame.pack(fill=tk.X, padx=10, pady=5)
        
        status_text = "🟢 Running" if self.worker.is_running() else "🔴 Stopped"
        tk.Label(info_frame, text=f"Status: {status_text}", font=("Arial", 12, "bold")).pack(side=tk.LEFT)
        
        if self.worker.last_update:
            last_update_str = self.worker.last_update.strftime("%Y-%m-%d %H:%M:%S")
            tk.Label(info_frame, text=f"Last Update: {last_update_str}").pack(side=tk.LEFT, padx=20)
        
        # Log area
        log_frame = tk.Frame(root)
        log_frame.pack(fill=tk.BOTH, expand=True, padx=10, pady=5)
        
        log_text = scrolledtext.ScrolledText(log_frame, wrap=tk.WORD, height=15)
        log_text.pack(fill=tk.BOTH, expand=True)
        log_text.insert(tk.END, "\n".join(self.status_log) if self.status_log else "No logs yet")
        log_text.config(state=tk.DISABLED)
        
        # Buttons
        btn_frame = tk.Frame(root)
        btn_frame.pack(fill=tk.X, padx=10, pady=5)
        
        if self.worker.is_running():
            tk.Button(btn_frame, text="Stop Worker", command=self.stop_worker_gui).pack(side=tk.LEFT, padx=5)
        else:
            tk.Button(btn_frame, text="Start Worker", command=self.start_worker_gui).pack(side=tk.LEFT, padx=5)
        
        tk.Button(btn_frame, text="Close", command=root.destroy).pack(side=tk.RIGHT, padx=5)
        
        root.mainloop()
    
    def start_worker_gui(self):
        """Start worker from GUI"""
        if self.worker.start():
            self.on_status_update("Worker started")
            self.update_menu()
        else:
            messagebox.showwarning("Warning", "Worker is already running")
    
    def stop_worker_gui(self):
        """Stop worker from GUI"""
        if self.worker.stop():
            self.on_status_update("Worker stopped")
            self.update_menu()
        else:
            messagebox.showwarning("Warning", "Worker is not running")
    
    def start_worker(self, icon=None, item=None):
        """Start worker from tray menu"""
        if self.worker.start():
            self.on_status_update("Worker started")
            self.update_menu()
    
    def stop_worker(self, icon=None, item=None):
        """Stop worker from tray menu"""
        if self.worker.stop():
            self.on_status_update("Worker stopped")
            self.update_menu()
    
    def update_menu(self):
        """Update tray menu based on worker status"""
        if self.icon:
            menu = self.create_menu()
            self.icon.menu = menu
    
    def create_menu(self):
        """Create system tray menu"""
        status_text = "🟢 Running" if self.worker.is_running() else "🔴 Stopped"
        
        menu_items = [
            pystray.MenuItem(f"Status: {status_text}", None, enabled=False),
            pystray.Menu.SEPARATOR,
            pystray.MenuItem("Show Status", self.show_status),
            pystray.Menu.SEPARATOR,
        ]
        
        if self.worker.is_running():
            menu_items.append(pystray.MenuItem("Stop Worker", self.stop_worker))
        else:
            menu_items.append(pystray.MenuItem("Start Worker", self.start_worker))
        
        menu_items.extend([
            pystray.Menu.SEPARATOR,
            pystray.MenuItem("Exit", self.quit_app)
        ])
        
        return pystray.Menu(*menu_items)
    
    def quit_app(self, icon=None, item=None):
        """Quit application"""
        if self.worker.is_running():
            self.worker.stop()
        if self.icon:
            self.icon.stop()
    
    def run(self):
        """Run system tray app"""
        if not HAS_PYSTRAY:
            print("Error: pystray not installed. Cannot run system tray app.")
            print("Install with: pip install pystray pillow")
            return
        
        # Generate summary immediately on start
        self.worker.generate_summary()
        
        # Start worker
        self.worker.start()
        
        # Create icon
        image = self.create_icon_image()
        menu = self.create_menu()
        
        self.icon = pystray.Icon("AI Worker", image, "AI Daily Summary Generator", menu)
        self.icon.run()


def main():
    """Main entry point"""
    print("AI Daily Summary Generator - GUI Version")
    print("Starting system tray application...")
    print("Look for the icon in your system tray (near clock)")
    print("Right-click the icon to access menu")
    
    app = SystemTrayApp()
    try:
        app.run()
    except KeyboardInterrupt:
        print("\nShutting down...")
        app.quit_app()
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()

